name: Build Online Boutique Images
on:
  workflow_dispatch:
jobs:
  checkout-code:
    runs-on: ubuntu-latest
    steps:
    #pull code
       - name: Checkout code
         uses: actions/checkout@v3
    #docker login
       - name: Login to Docker Hub
         uses: docker/login-action@v3
         with:
           username: "${{ vars.DOCKERHUB_USERNAME }}"
           password: ${{ secrets.DOCKERHUB_TOKEN }}
    #build         
    #   - name: Build Image\
    #     working-directory: /home/runner/work/kube-project/kube-project/online-boutique/src/adservice
    #     run: docker build -t nvyakimov/adservice:1.0.0 .
    #push
    #   - name: Push Image
    #     run: docker push nvyakimov/adservice:1.0.0
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: tale/kubectl-action@v1
      with:
        base64-kube-config: ${{ secrets.MINIKUBE_CONFIG }}
    - run: kubectl get pods
    #- run: kubectl create ns test

        
