name: Build Online Boutique Images
on:
  workflow_dispatch:
jobs:
  checkout-code:
    runs-on: ubuntu-latest
    steps:
    #pull code
       - name: Checkout code
         uses: actions/checkout@v3
    #docker login
       - name: Login to Docker Hub
         uses: docker/login-action@v3
         with:
           username: "${{ vars.DOCKERHUB_USERNAME }}"
           password: ${{ secrets.DOCKERHUB_TOKEN }}
    #build         
    #   - name: Build Image\
    #     working-directory: /home/runner/work/kube-project/kube-project/online-boutique/src/adservice
    #     run: docker build -t nvyakimov/adservice:1.0.0 .
    #push
    #   - name: Push Image
    #     run: docker push nvyakimov/adservice:1.0.0
       - name: cp kubeconfig
         run:  echo "${{ secrets.MINIKUBE_CONFIG }}" > /home/runner/work/kube-project/kube-project/online-boutique/kubeconfig
       - name: cat kubeconfig
         run:  cat /home/runner/work/kube-project/kube-project/online-boutique/kubeconfig
       - name: create ns
         run:  kubectl --kubeconfig /home/runner/work/kube-project/kube-project/online-boutique/kubeconfig create ns adservice
       - name: deploy
         run:  kubectl --kubeconfig /home/runner/work/kube-project/kube-project/online-boutique/kubeconfig -n adservice run adservice --image=nvyakimov/adservice:1.0.0
    # set kubernetes cluster
       #- name: Set Kubeconfig
         #run: yc managed-kubernetes cluster get-credentials --id catg9d7ku0ovrqfhd3gd --external
    # deploy app
       #- name: Deploy
         #run: kubectl -n online-boutique apply -f adservice.yaml

        
