name: Build Online Boutique Images
on:
 workflow_dispatch:

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout code
       uses: actions/checkout@v3
     - name: Check code base
       uses: docker://github/super-linter:v2.1.0
#  build-and-push-image:
#    runs-on: ubuntu-latest
#    needs: [linter]
#    if: ${{ always() }}
#    steps:
#    #pull code
#      - name: Checkout code
#        uses: actions/checkout@v3
#    #docker login
#      - name: Login to Docker Hub
#        uses: docker/login-action@v3
#        with:
#          username: "${{ vars.DOCKERHUB_USERNAME }}"
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#    #build     
#      - name: Build Image
#        working-directory: /home/runner/work/kube-project/kube-project/online-boutique/src/adservice
#        run: docker build -t nvyakimov/adservice:1.0.0 .
#    #push
#      - name: Push Image
#        run: docker push nvyakimov/adservice:1.0.0
#  deploy:
#   runs-on: ubuntu-latest
#   needs: [build-and-push-image]
#   if: ${{ always() }}
#   steps:
#    - name: Checkout code
#      uses: actions/checkout@v3
#    - name: Create kubeconfig
#      run: |
#        mkdir ${HOME}/.kube
#        echo "${{ secrets.KUBE_CA }}" | base64 --decode > ${HOME}/.kube/ca.pem
#        echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > ${HOME}/.kube/config
#        cat ${HOME}/.kube/config
#    - name: Use context
#      run: kubectl config use-context yc-kuber-cluster
#    - name: Deploy to K8s
#      run: kubectl run adservice --image nvyakimov/adservice:1.0.0
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      #pull code
      - name: Checkout code
        uses: actions/checkout@v3
      #docker login
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: "${{ vars.DOCKERHUB_USERNAME }}"
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      #build&push
      - name: Build and Push Images
        working-directory: /home/runner/work/kube-project/kube-project/online-boutique/src
        run: |
          for app_dir *; do
            echo "Building and pushing $app_dir image..."
            cd $app_dir
            docker build -t nvyakimov/$app_dir:${{ runner.workflow.ref_name }} .
            docker push nvyakimov/$app_dir:${{ runner.workflow.ref_name }}
          done
