name: Build Online Boutique Images
on:
  workflow_dispatch:


jobs:
#pull code
  checkout-code:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout code
         uses: actions/checkout@v3
       - name: Check if code exists
         run: ls -l /home/runner/work/kube-project/kube-project
 #docker login 
  docker-login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: "${{ vars.DOCKERHUB_USERNAME }}"
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  #build image
  build-images:
    runs-on: ubuntu-latest
    #defaults:
    #  run:
    #    working-directory: /home/runner/work/kube-project/kube-project/online-boutique/src/adservice
    steps:
      - name: ls
        run: ls -l /home/runner/work/kube-project/kube-project
      
      - name: ls
        run: ls -l /home/runner/work/kube-project/kube-project/online-boutique
        
      - name: Build Image
        run: docker build -t nvyakimov/adservice:1.0.0 .

      - name: Push Image
        run: docker push
  deploy-app:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: /home/runner/work/kube-project/kube-project/microservices-demo/kubernetes-manifests
    steps:
      - name: Set Kubeconfig
        run: yc managed-kubernetes cluster get-credentials --id catg9d7ku0ovrqfhd3gd --external
      - name: Deploy
        run: kubectl -n online-boutique apply -f adservice.yaml
    


