name: Deploy Observability
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Create kubeconfig
      run: |
        mkdir ${HOME}/.kube
        echo "${{ secrets.KUBE_CA }}" | base64 --decode > ${HOME}/.kube/ca.pem
        echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > ${HOME}/.kube/config
        cat ${HOME}/.kube/config
    - name: Use context
      run: kubectl config use-context yc-kuber-cluster
      #get current tag
    - name: Get current app version by tag
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Install kiali
      working-directory: /home/runner/work/kube-project/kube-project/istio
      run: kubectl apply -f addons/prometheus.yaml && kubectl apply -f addons/kiali.yaml
    - name: Install logging
      working-directory: /home/runner/work/kube-project/kube-project
      run: |
        helm repo add fluent https://fluent.github.io/helm-charts && \
        helm repo add opensearch https://opensearch-project.github.io/helm-charts/ && \
        helm repo update && \
        helm -n logging upgrade --install fluent-bit fluent/fluent-bit -f observability/fluent-bit.yml --create-namespace && \
        helm -n logging upgrade --install logstash observability/logstash/  && \
        helm -n logging upgrade --install opensearch opensearch/opensearch -f observability/opensearch.yml  && \
        helm -n logging upgrade --install opensearch-dashboards opensearch/opensearch-dashboards -f observability/opensearch-dashboard.yml
  notify-success:
    runs-on: ubuntu-latest    
    needs: [deploy]
    if: ${{ success() }}    
    steps:
      #get current tag      
    - name: Get current app version by tag
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV      
    - name: send telegram message on push
      uses: appleboy/telegram-action@master        
      with:
        to: ${{ secrets.TELEGRAM_TO }}          
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |            
          Успешно выполнен релиз приложений для мониторинга.
  notify-failure:
    runs-on: ubuntu-latest
    needs: [deploy]    
    if: ${{  failure() }}
    steps:      
      #get current tag
      - name: Get current app version by tag        
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: send telegram message on push        
        uses: appleboy/telegram-action@master
        with:          
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}          
          message: |
            Релиз приложений для мониторинга не выполнен. Произошла ошибка.