name: Deploy Online Boutique
on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout code
       uses: actions/checkout@v3
     - name: Check code base
       uses: docker://github/super-linter:v2.1.0
  build-and-push-image:
    needs: [linter]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      #pull code
      - name: Checkout code
        uses: actions/checkout@v3
      #get current tag
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Test
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
      #docker login
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: "${{ vars.DOCKERHUB_USERNAME }}"
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      #build&push
      - name: Build and Push Images
        working-directory: /home/runner/work/kube-project/kube-project/online-boutique/src
        run: |
          for app_dir in *; do
            echo "Building and pushing $app_dir image..."
            docker build -t nvyakimov/$app_dir:"${{ env.RELEASE_VERSION }}" $app_dir
            docker push nvyakimov/$app_dir:"${{ env.RELEASE_VERSION }}"
            echo "###############################"
          done
  deploy:
    runs-on: ubuntu-latest
    needs: [build-and-push-image]
    if: ${{ always() }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Create kubeconfig
      run: |
        mkdir ${HOME}/.kube
        echo "${{ secrets.KUBE_CA }}" | base64 --decode > ${HOME}/.kube/ca.pem
        echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > ${HOME}/.kube/config
        cat ${HOME}/.kube/config
    - name: Use context
      run: kubectl config use-context yc-kuber-cluster
    - name: Deploy to K8s
      working-directory: /home/runner/work/kube-project/kube-project/online-boutique/helm-chart
      run: helm -n onlineboutique upgrade -f values.yaml onlineboutique . --install --create-namespace
  notify:
    runs-on: ubuntu-latest
    #needs: [deploy]
    #if: ${{ always() }}
    steps:
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Успешно выполнен релиз приложения OnlineBoutique новой версии "${{ env.RELEASE_VERSION }}".
