name: Run Terraform
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Run Terraform init
        run: terraform init

      - name: Run Terraform plan
        run: terraform plan -out=tfplan

      - name: Approve Terraform plan (manual)
        uses: actions/approval@v1
        with:
          title: "Approve Terraform plan?"
          body: "Review the changes proposed in the Terraform plan."
          approvals: 1

      - name: Apply Terraform plan
        run: terraform apply "tfplan"

      - name: Output Terraform state
        run: terraform show -json > terraform.json
