name: Run managed kubernetes cluster in Yandex.Cloud
on:
  workflow_dispatch:

jobs:
  run-kuber-cluster:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: /home/runner/work/kube-project/kube-project/terraform/run-yc-managed-kuber
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Run Terraform init
        run: terraform init

      - name: Run Terraform plan
        run: terraform plan -var="token=${{ secrets.TOKEN }}" -var="cloud_id=${{ secrets.CLOUD_ID }}" -var="cloud_catalog_title=${{ vars.CLOUD_CATALOG_TITLE }}" -var="zone=${{ vars.ZONE }}" -var="folder_id=${{ secrets.YC_FOLDER_ID }}" -out=tfplan

      - name: Run Terraform validate
        run: terraform validate

      - name: Apply Terraform plan
        run: terraform apply "tfplan"
        
      - name: Output Terraform state
        run: terraform show -json > terraform.json
  install-kube-ingress-controller:
    runs-on: ubuntu-latest
    #needs: [run-kuber-cluster]
    #if: ${{ always() }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create kubeconfig
        run: |
          mkdir ${HOME}/.kube
          echo "${{ secrets.KUBE_CA }}" | base64 --decode > ${HOME}/.kube/ca.pem
          echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > ${HOME}/.kube/config
          cat ${HOME}/.kube/config
      - name: Use context
        run: kubectl config use-context yc-kuber-cluster
      - name: Install ingress nginx
        run: |
          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx && \
          helm repo update && \
          helm install ingress-nginx ingress-nginx/ingress-nginx
      - name: Check external cluster ip
        run: kubectl get svc