name: Run managed kubernetes cluster in Yandex.Cloud
on:
  workflow_dispatch:

jobs:
  run-kuber-cluster:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: /home/runner/work/kube-project/kube-project/terraform/run-yc-managed-kuber
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Run Terraform init
        run: terraform init

      - name: Run Terraform plan
        run: terraform plan -var="token=${{ secrets.TOKEN }}" -var="cloud_id=${{ secrets.CLOUD_ID }}" -var="cloud_catalog_title=${{ vars.CLOUD_CATALOG_TITLE }}" -var="zone=${{ vars.ZONE }}" -var="folder_id=${{ secrets.YC_FOLDER_ID }}" -out=tfplan

      - name: Run Terraform validate
        run: terraform validate

      - name: Apply Terraform plan
        run: terraform apply "tfplan"
        
      - name: Output Terraform state
        run: terraform show -json > terraform.json
  notify-success:
    runs-on: ubuntu-latest    
    needs: [run-kuber-cluster]
    if: ${{ success() }}    
    steps:
    - name: send telegram message on push
      uses: appleboy/telegram-action@master        
      with:
        to: ${{ secrets.TELEGRAM_TO }}          
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |            
          Успешно развернут kubernetes кластер в Яндекс.Облаке".
  notify-failure:
    runs-on: ubuntu-latest
    needs: [run-kuber-cluster]  
    if: ${{  failure() }}
    steps:
      - name: send telegram message on push        
        uses: appleboy/telegram-action@master
        with:          
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}          
          message: |
            kubernetes кластер в Яндекс.Облаке не развернут. Произошла ошибка.